import nav from '@/views/nav.vue';
const list=[
    {
        path:"/my/grzl/aqwt",
        component:()=>import('@/views/my/个人资料/安全问题.vue'),
        meta:{
            需要登录:true
        }
    },{
        path:"/my/yhk",
        component:()=>import('@/views/my/个人资料/银行卡设置.vue'),
        meta:{
            需要登录:true
        }
    },
    {
        path:"/my/cardbag",
        component:()=>import('@/views/my/个人资料/银行卡.vue'),
        meta:{
            需要登录:true
        }
    },
    {
        path:"/my/addBankCard",
        component:()=>import('@/views/my/个人资料/添加银行卡.vue'),
        meta:{
            需要登录:true
        }
    },
    {
        path:"/my/basic",
        component:()=>import('@/views/my/个人资料/个人信息.vue'),
        meta:{
            需要登录:true
        }
    },{
        path:"/my/plsz",
        component:()=>import('@/views/my/个人资料/偏好设置.vue'),
        meta:{
            需要登录:true
        }
    },{
        path:"/my/ztsz",
        component:()=>import('@/views/my/个人资料/主题设置.vue'),
        meta:{
            需要登录:true
        }
    },
    {
        
        path:'/my/basic/qq',
        component:()=>import('@/views/my/个人资料/修改qq.vue'),
        meta:{
            需要登录:true
        }
    },
    {
        path:'/my/basic/name',
        component:()=>import('@/views/my/个人资料/修改昵称.vue'),
        meta:{
            需要登录:true
        }
    },
    {
        path:'/my/basic/picture',
        component:()=>import('@/views/my/个人资料/修改头像.vue'),
        meta:{
            需要登录:true
        }
    }
]
export default list